from .admin import Admin
from .parent import Parent
from .student import Student
from .attendance import Attendance
from .homework import Homework
from .score import Score
from .meal import Meal
from .ai_analysis import AIAnalysis
from .evaluation import Evaluation
